### GET request to example server
GET http://localhost:8081/todo

### POST request to add todo
POST http://localhost:8081/todo

{
    "item": "get groceries"
}

### GET request to search todo
GET http://localhost:8081/search?q=Shop

### DELETE todo based on id
### DELETE http://localhost:8081/todo/1

### DELETE todo based on non existed id
### DELETE http://localhost:8081/todo/3
